const wallpaperModes = Object.freeze({
  none: "none",
  random: "random",
  builtin: "builtin",
  url: "url",
  local: "local"
});

const wallpaperDefaults = Object.freeze({
  wallpaper: "",
  wallpaperMode: wallpaperModes.none,
  wallpaperId: "",
  wallpaperUrl: "",
  wallpaperLocalId: "",
  wallpaperRandomDate: "",
  wallpaperRandomUrl: ""
});

globalThis.BETTERLD_CONFIG = Object.freeze({
  homepagePath: "/",
  routePollMs: 500,
  syncDebounceMs: 160,
  syncQuotaBytes: 102400,
  fontRecommendedStack: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  listControlsScrollThreshold: 8,
  excerptRootMargin: "240px 0px",
  excerptMaxCharacters: 2400,
  excerptLoadingLabel: "正在读取正文预览…",
  excerptPlaceholder: "正文预览暂不可用",
  excerptEmptyLabel: "正文为空",
  authorLoadingLabel: "作者信息加载中…",
  authorPlaceholder: "作者信息暂不可用",
  topicRequestRetryCount: 2,
  topicRequestRetryDelayMs: 1500,
  topicRequestRecoveryCount: 1,
  topicRequestRecoveryDelayMs: 10000,
  storageKey: "betterld.settings",
  syncMetadataKey: "betterld.sync-meta",
  wallpaperLocalStorageKey: "betterld.local-wallpaper",
  wallpaperRemoteCacheKey: "betterld.remote-wallpaper-cache",
  wallpaperRandomSeedPattern: "https://picsum.photos/seed/{date}/2560/1440/?nature",
  wallpaperUpload: Object.freeze({
    maxWidth: 2560,
    maxHeight: 1440,
    quality: 0.9,
    maxBytes: 8 * 1024 * 1024
  }),
  wallpaperModes,
  wallpaperCatalog: Object.freeze([
    {
      id: "lorem-picsum-random",
      mode: wallpaperModes.random,
      name: "LoremPicsum Random Image",
      url: "https://picsum.photos/2560/1440/?nature",
      thumbnail: "https://picsum.photos/2560/1440/?nature"
    },
    {
      id: "rocky-mountain-cloudscape",
      mode: wallpaperModes.builtin,
      name: "Nicolas Lafargue - Rocky Mountain Cloudscape",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/rocky-mountain-cloudscape.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/rocky-mountain-cloudscape-thumbnail.jpg"
    },
    {
      id: "green-white-mountains",
      mode: wallpaperModes.builtin,
      name: "Zongnan Bao- Green white mountains",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/green-white-mountains.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/green-white-mountains-thumbnail.jpg"
    },
    {
      id: "night-sky-stars",
      mode: wallpaperModes.builtin,
      name: "Colin Watts - Night Sky Stars",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/night-sky-stars.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/night-sky-stars-thumbnail.jpg"
    },
    {
      id: "sailboats-at-exumas",
      mode: wallpaperModes.builtin,
      name: "Ryan Geller - Sailboats moored at Land and Sea Park in The Exumas",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/sailboats-moored-at-the-exumas.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/sailboats-moored-at-the-exumas-thumbnail.jpg"
    },
    {
      id: "outer-space-photo",
      mode: wallpaperModes.builtin,
      name: "NASA - Outer Space Photo",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/outer-space-photo.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/outer-space-photo-thumbnail.jpg"
    },
    {
      id: "bml2019-vr",
      mode: wallpaperModes.builtin,
      name: "BML2019 VR (pid: 74271400)",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/bml2019-vr.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/bml2019-vr-thumbnail.jpg"
    },
    {
      id: "2020-new-year-festival",
      mode: wallpaperModes.builtin,
      name: "2020 拜年祭活动",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/2020-拜年祭活动.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/2020-拜年祭活动-thumbnail.jpg"
    },
    {
      id: "2020-bdf",
      mode: wallpaperModes.builtin,
      name: "2020 BDF",
      url: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/2020-bdf.jpg",
      thumbnail: "https://cdn.jsdelivr.net/gh/BewlyBewly/Imgs/wallpapers/2020-bdf-thumbnail.jpg"
    }
  ]),
  wallpaperDefaults,
  themeCatalog: Object.freeze([
    {
      id: "material-purple",
      name: "Material Purple",
      lightPrimary: "#6750a4",
      darkPrimary: "#d0bcff",
      lightOnPrimary: "#ffffff",
      darkOnPrimary: "#381e72"
    },
    {
      id: "ocean-blue",
      name: "Ocean Blue",
      lightPrimary: "#315f90",
      darkPrimary: "#a8c8f0",
      lightOnPrimary: "#ffffff",
      darkOnPrimary: "#12304f"
    },
    {
      id: "forest-green",
      name: "Forest Green",
      lightPrimary: "#386a20",
      darkPrimary: "#9dd67e",
      lightOnPrimary: "#ffffff",
      darkOnPrimary: "#17380b"
    },
    {
      id: "sunset-orange",
      name: "Sunset Orange",
      lightPrimary: "#8b5000",
      darkPrimary: "#ffb95c",
      lightOnPrimary: "#ffffff",
      darkOnPrimary: "#472900"
    }
  ]),
  gridBreakpoints: Object.freeze({
    base: 0,
    sm: 560,
    md: 800,
    lg: 1100,
    xl: 1400,
    xxl: 1800
  }),
  topicNavigationItems: Object.freeze([
    "latest",
    "new",
    "unread",
    "hot",
    "top",
    "posted",
    "read",
    "bookmarks",
    "categories"
  ]),
  topicCardContextMenuActions: Object.freeze([
    "openCurrentTab",
    "openNewTab",
    "openBackground",
    "openDrawer",
    "copyTopicUrl",
    "copyCleanUrl",
    "copyTopicId",
    "openCategory",
    "openAuthor"
  ]),
  actionRailItems: Object.freeze(["settings", "theme", "top", "refresh"]),
  settingsEnums: Object.freeze({
    themeMode: Object.freeze(["auto", "system", "light", "dark", "scheduled"]),
    fontMode: Object.freeze(["default", "recommended", "custom"]),
    fontScope: Object.freeze(["own", "managed"]),
    shadowMode: Object.freeze(["default", "none", "custom"]),
    gridMode: Object.freeze(["auto", "fixed"]),
    topicListLayoutMode: Object.freeze(["reading", "cards", "native"]),
    topicTitleFontSize: Object.freeze(["responsive", "small", "base", "large"]),
    topicAuthorFontSize: Object.freeze(["small", "base", "large"]),
    topicMetaFontSize: Object.freeze(["small", "base", "large"]),
    topicNavigationAlignment: Object.freeze(["left", "center"]),
    headerVisualMode: Object.freeze(["native", "transparent", "frosted", "solid"]),
    sidebarPosition: Object.freeze(["original", "right"]),
    actionRailPosition: Object.freeze(["left", "right", "bottom"]),
    actionRailVisibility: Object.freeze(["always", "auto", "hidden"]),
    topicCardOpenMode: Object.freeze(["currentTab", "newTab", "background", "drawer"]),
    navigationOpenMode: Object.freeze(["currentTab", "newTab"]),
    searchOpenMode: Object.freeze(["currentTab", "newTab"]),
    notificationOpenMode: Object.freeze(["page", "newTab"]),
    topicFilterMode: Object.freeze(["hide", "include"]),
    searchMode: Object.freeze(["native", "cards"]),
    searchResultsPaginationMode: Object.freeze(["scroll", "pagination"]),
    searchPageWallpaperMode: Object.freeze(["inherit", "builtin", "url"]),
    touchOptimization: Object.freeze(["auto", "on", "off"]),
    language: Object.freeze(["zh-CN", "en-US"]),
    wallpaperRemoteCacheDays: Object.freeze([0, 1, 7, 30])
  }),
  settingsDefaults: Object.freeze({
    ...wallpaperDefaults,
    settingsVersion: 2,
    language: "zh-CN",
    maskOpacity: 0.42,
    blurPx: 18,
    cardOpacity: 0.82,
    themeMode: "auto",
    themeScheduleStart: "18:00",
    themeScheduleEnd: "07:00",
    themeColor: "#6750a4",
    darkModeBaseColor: "#141218",
    useGradientThemeColorBackground: false,
    liquidSegmentIndicatorEnabled: false,
    frostedGlassEnabled: true,
    sidebarCoverBlurEnabled: true,
    surfaceBlurPx: 16,
    shadowMode: "default",
    shadowHeight: 1,
    shadowCurve: [
      { position: 0, opacity: 0.12 },
      { position: 0.5, opacity: 0.08 },
      { position: 1, opacity: 0 }
    ],
    fontMode: "default",
    fontScope: "own",
    fontFamily: "",
    removeChinesePunctuationIndent: false,
    customCssEnabled: false,
    customCss: "",
    wallpaperRemoteCacheDays: 0,
    applyToUnmanagedPages: false,
    gridMode: "auto",
    cardMinSize: 280,
    cardSideGutter: 24,
    gridGap: 16,
    gridColumns: {
      base: 1,
      sm: 2,
      md: 3,
      lg: 4,
      xl: 5,
      xxl: 6
    },
    showTopicAvatar: true,
    showTopicAuthor: true,
    showTopicCategory: true,
    showTopicExcerpt: true,
    showTopicMeta: true,
    showTopicUnreadState: true,
    showTopicPinnedState: true,
    topicListLayoutMode: "reading",
    topicCardContextMenuConfig: [
      { key: "openCurrentTab", visible: true, order: 0 },
      { key: "openNewTab", visible: true, order: 1 },
      { key: "copyTopicUrl", visible: true, order: 2 },
      { key: "copyTopicId", visible: true, order: 3 }
    ],
    topicTitleFontSize: "responsive",
    topicAuthorFontSize: "base",
    topicMetaFontSize: "base",
    topicNavigationConfig: [],
    topicNavigationAlignment: "left",
    topicNavigationSticky: true,
    showTopicNavigationCounts: true,
    headerVisible: true,
    headerVisualMode: "native",
    autoHideHeader: false,
    sidebarPosition: "original",
    autoHideSidebar: false,
    showSettingsTrigger: true,
    showThemeToggle: true,
    actionRailEnabled: false,
    actionRailPosition: "right",
    actionRailVisibility: "auto",
    actionRailGlow: true,
    actionRailItemsConfig: [
      { key: "settings", visible: true, order: 0 },
      { key: "theme", visible: false, order: 1 },
      { key: "top", visible: false, order: 2 },
      { key: "refresh", visible: false, order: 3 }
    ],
    showBackToTopButton: false,
    showRefreshButton: false,
    separateNavigationActions: true,
    enableUndoRefresh: false,
    topicCardOpenMode: "currentTab",
    navigationOpenMode: "currentTab",
    searchOpenMode: "currentTab",
    notificationOpenMode: "page",
    drawerCloseOnOverlay: true,
    drawerCloseOnEscape: true,
    topicFilterEnabled: false,
    topicFilterMode: "hide",
    topicTitleRules: [],
    topicAuthorRules: [],
    topicCategoryRules: [],
    searchMode: "native",
    searchHistoryEnabled: false,
    searchRecommendationEnabled: false,
    searchFocusDimming: false,
    searchFocusBlur: false,
    searchResultsPaginationMode: "scroll",
    searchPageWallpaperMode: "inherit",
    searchPageWallpaperId: "",
    searchPageWallpaperUrl: "",
    searchHistory: [],
    touchOptimization: "auto",
    enableHorizontalNavigationScroll: true,
    showHomeButtonInTouchMode: true,
    shortcutsEnabled: false,
    shortcuts: {
      refreshTopics: "R",
      openSettings: "",
      toggleListControls: ""
    },
    syncEnabled: false
  }),
  settingsLimits: Object.freeze({
    maskOpacity: Object.freeze({ min: 0, max: 0.8, step: 0.01 }),
    blurPx: Object.freeze({ min: 0, max: 32, step: 1 }),
    cardOpacity: Object.freeze({ min: 0.55, max: 0.95, step: 0.01 }),
    surfaceBlurPx: Object.freeze({ min: 0, max: 32, step: 1 }),
    shadowHeight: Object.freeze({ min: 0, max: 2, step: 0.1 }),
    shadowCurveOpacity: Object.freeze({ min: 0, max: 1, step: 0.01 }),
    cardMinSize: Object.freeze({ min: 240, max: 480, step: 8 }),
    cardSideGutter: Object.freeze({ min: 16, max: 48, step: 4 }),
    gridGap: Object.freeze({ min: 8, max: 32, step: 4 }),
    gridColumn: Object.freeze({ min: 1, max: 12, step: 1 }),
    fontFamily: Object.freeze({ maxLength: 200 }),
    customCss: Object.freeze({ maxLength: 64 * 1024 }),
    ruleKeyword: Object.freeze({ maxLength: 200 }),
    ruleRemark: Object.freeze({ maxLength: 200 }),
    ruleCount: Object.freeze({ max: 64 }),
    shortcut: Object.freeze({ maxLength: 24 }),
    searchHistory: Object.freeze({ maxItems: 50, maxLength: 200 })
  })
});